#!/usr/bin/env python3
"""Generate TUPLE_INDEX.md: every predeliberated tuple, its owning agent,
and the playbooks that agent participates in - the drill-down table for the
decision tree. Derived from the generators (gen_meta's D, playbook SKILL.md
step tables), never hand-maintained. Regenerate after any tuple or playbook
change: python3 gen_tuple_index.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))

# tuple layer from its source of truth (import executes no writes; gen_meta
# writes only under __main__)
import gen_meta  # noqa: E402

AGENT_DIRS = {d[:2]: d for d in os.listdir(HERE) if re.match(r"^\d{2}-", d)}

# playbook -> participating agents, parsed from each SKILL.md step table
# (the agent column, e.g. "| 1 | 20→01 | ..." or "| 2a | 07 | ...")
pb_agents = {}
for d in sorted(os.listdir(os.path.join(HERE, "playbooks"))):
    p = os.path.join(HERE, "playbooks", d, "SKILL.md")
    if not os.path.exists(p):
        continue
    nums = set()
    for line in open(p, encoding="utf-8"):
        m = re.match(r"\|\s*\w+\s*\|\s*([0-9→>,\s-]+?)\s*\|", line)
        if m:
            nums.update(re.findall(r"\b(\d{2})\b", m.group(1)))
    pb_agents[d.split("-")[0]] = nums

agent_pbs = {}
for pb, nums in pb_agents.items():
    for n in nums:
        agent_pbs.setdefault(n, set()).add(pb)

out = ["# TUPLE_INDEX - drill-down: tuple -> agent -> connected playbooks",
       "",
       "Generated by gen_tuple_index.py from gen_meta.py (tuple source of",
       "truth) and the playbook step tables. Do not hand-edit.",
       "",
       "Root structure: the PRE-TEXT rule governs entry (no suitable tuple,",
       "or an uncertain match = STOP, ask the human). Below it, every tuple",
       "with its crossing, answer, owning agent, and the playbooks where",
       "that agent executes - the (x, y) pairs of the process system.",
       ""]
total = 0
for num in sorted(gen_meta.D):
    d = AGENT_DIRS.get(num, num)
    pbs = ", ".join(sorted(agent_pbs.get(num, []))) or \
          ("all (transport/queues)" if num == "00" else "none (tuple-layer only)")
    out.append(f"## Agent {num} - {d.split('-', 1)[1] if '-' in d else d}")
    out.append(f"Connected playbooks: {pbs}")
    out.append("")
    out.append("| # | Crossing | Predeliberated answer |")
    out.append("|---|---|---|")
    for i, (c, a) in enumerate(gen_meta.D[num], 1):
        out.append(f"| {num}.{i:02d} | {c} | {a} |")
        total += 1
    out.append("")
out.append(f"Total tuples: {total}. Swarm-wide tuples: SWARM.md. "
           f"Coverage map: TASK_INVENTORY.md.")
open(os.path.join(HERE, "TUPLE_INDEX.md"), "w", encoding="utf-8").write(
    "\n".join(out) + "\n")
print(f"TUPLE_INDEX.md: {total} tuples, {len(pb_agents)} playbooks indexed")
